import type { Metadata } from "next";
import { Jaro } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const jaro = Jaro({
  variable: "--font-jaro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jaro.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
