import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header/Header";
import { Jaro, Jaldi } from "next/font/google";

const jaro = Jaro({ subsets: ["latin"], variable: "--font-jaro" });

const jaldi = Jaldi({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: "--font-jaldi"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jaro.variable} ${jaldi.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
