import type { Metadata } from "next";
import { Jaldi, Jaro } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const jaldi = Jaldi({
  weight: ["400", "700"],
  variable: "--font-jaldi",
  subsets: ["latin"],
});

const jaro = Jaro({
  variable: "--font-jaro",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jaldi.variable} ${jaro.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
